export enum EAppRouter {
  root = "/",
  about = "/about",
  tags = "/tags",
  admin = "/admin",
  latest = "/latest",
  top = "/top/week",
  enter = "/enter",
  podcasts = "/podcasts",
  videos = "/videos",
  help = "/help",
  getting = "/help/getting",
  customizing = "help/writing",
  reacting = "help/reacting",
  badges = "help/badges",
  advertising = "help/advertising",
  spamandAbuse = "help/spamandAbuse",
  bugs = "help/bugs",
  funStuff = "help/FunStuff",
  community = "help/community",
  organizations = "help/organizations",
  advertise = "/advertise",
  devshowcase = "/devshowcase",
  contact = "/contact",
  codeofconduct = "/code-of-conduct",
  privacy = "/privacy",
  terms = "/terms",
}

