export enum EAppRouter {
  root = "/",
  about = "/about",
  tags = "/tags",
  admin = "/admin",
  latest = "/latest",
  top = "/top/week",
  enter = "/enter",
  podcasts = "/podcasts",
  videos = "/videos",
  help = "/help",
  advertise = "/advertise",
  devshowcase = "/devshowcase",
  contact = "/contact",
  codeofconduct = "/code-of-conduct",
  privacy = "/privacy",
  terms = "/terms",
  getting = "/help/getting",
  writing = "/help/writing",
  customizing = "/help/customizing",
  reacting = "/help/reacting",
  badges = "/help/badges",
  advertising = "/help/advertising",
  bugs = "/help/bugs",
  funStuff = "/help/funStuff",
  community = "/help/community",
  organizations = "/help/organizations",
  spamAndAbuse = "/help/spamAndAbuse",
}

