export interface Tags {
  id: number
  tag: string
  number: string
  content: string
  follow: string
  hide: string
}

export const ListTags: Tags[] = [
  {
    id: 0,
    follow: "follow",
    hide: "hide",
    tag: "#webdev",
    number: "159,873",
    content: "Because the internet",
  },
  {
    id: 1,
    follow: "follow",
    hide: "hide",
    tag: "#javascript",
    number: "200,873",
    content: "Once relegated to the browser as one of the 3 core technologies of the web, JavaScript can now be found almost",
  },
  {
    id: 2,
    follow: "follow",
    hide: "hide",
    tag: "#beginners",
    number: "179,271",
    content: "A journey of a thousand miles begins with a single step. -Chinese Proverb",
  },
  {
    id: 3,
    follow: "follow",
    hide: "hide",
    tag: "#programming",
    number: "167,289",
    content: "The magic behind computers",
  },
  {
    id: 4,
    follow: "follow",
    hide: "hide",
    tag: "#tutorial",
    number: "241,292",
    content: "Tutorial is a general purpose tag. We welcome all types of tutorial - code related or not! It's all about learning, and",
  },
  {
    id: 5,
    follow: "follow",
    hide: "hide",
    tag: "#React",
    number: "123,292",
    content: "Official tag for Facebook's React JavaScript library for building user interfaces",
  },
  {
    id: 6,
    follow: "follow",
    hide: "hide",
    tag: "#python",
    number: "50,000",
    content: "import antigravity",
  },
  {
    id: 7,
    follow: "follow",
    hide: "hide",
    tag: "#ai",
    number: "237,999",
    content: "Artificial intelligence leverages computers and machines to mimic the problem-solving and decision-making capabilities found in humans and in nature.",
  },
  {
    id: 8,
    follow: "follow",
    hide: "hide",
    tag: "#devops",
    number: "55,000",
    content: "Content centering around the shifting left of responsibility, deconstruction of responsibility silos, and the automation",
  },
  {
    id: 9,
    follow: "follow",
    hide: "hide",
    tag: "#discuss",
    number: "29,472",
    content: "Discussion threads targeting the whole community",
  },
  {
    id: 10,
    follow: "follow",
    hide: "hide",
    tag: "#productivity",
    number: "39,163",
    content: "Productivy includes tips on how to use tools and software , process  optimization, useful references, experience, and mindstate optimization.",
  },
  {
    id: 11,
    follow: "follow",
    hide: "hide",
    tag: "#aws",
    number: "30,049",
    content: "Amazon Web Service (AWS) is a collection of web service for computing, storage , machine learning, security, and",
  },
  {
    id: 12,
    follow: "follow",
    hide: "hide",
    tag: "#css",
    number: "33,550",
    content: "Cascading Style Sheets (CSS) is a simple language for adding style (e.g., fonts, colors, spacing) to HTML documents. It",
  },
  {
    id: 12,
    follow: "follow",
    hide: "hide",
    tag: "#opensource",
    number: "32,604",
    content: "May The Source Be With You! Articles about Open Source and Free Software as a philosophy, and its application to",
  },
  {
    id: 13,
    follow: "follow",
    hide: "hide",
    tag: "#typescript",
    number: "17,002",
    content: "Optional static type-checking for Javascript",
  },
  {
    id: 14,
    follow: "follow",
    hide: "hide",
    tag: "#typescript",
    number: "17,002",
    content: "Optional static type-checking for Javascript",
  },
  {
    id: 15,
    follow: "follow",
    hide: "hide",
    tag: "#machinelearning",
    number: "13,058",
    content: "A branch of artificial intelligence (Ai) and computer science which focuses on the use of data and algorithms to imitate th",
  },
  {
    id: 16,
    follow: "follow",
    hide: "hide",
    tag: "#node",
    number: "32,768",
    content: "A JavaScript runtime built on Chrome's V8 JavaScript engine.",
  },
  {
    id: 17,
    follow: "follow",
    hide: "hide",
    tag: "#java",
    number: "19,749",
    content: "More than just a cup of coffee, Java is a high-level, class-based, object-oriented programming language that is designed",
  },
  {
    id: 18,
    follow: "follow",
    hide: "hide",
    tag: "#career",
    number: "30,997",
    content: "This tag is for anything relating to careers! Job offers, workplace conflict, interviews, resumes, promotions, etc.",
  },

  {
    id: 19,
    follow: "follow",
    hide: "hide",
    tag: "#learning",
    number: "11,526",
    content: "“I have no special talent. I am only passionately curious.” - Albert Einstein",
  },
  {
    id: 20,
    follow: "follow",
    hide: "hide",
    tag: "#news",
    number: "42,070",
    content: "Expect to see announcements of new and updated products, services, and features for languages & frameworks. You also will find high-level news relevant to the",
  },
  {
    id: 21,
    follow: "follow",
    hide: "hide",
    tag: "#datascience",
    number: "10,989",
    content: "Data Science allows us to extract meaning from and interpret data.",
  },
  {
    id: 22,
    follow: "follow",
    hide: "hide",
    tag: "#testing",
    number: "16,538",
    content: "Find those bugs before your users do!",
  },
  {
    id: 23,
    follow: "follow",
    hide: "hide",
    tag: "#database",
    number: "17,002",
    content: "Posts on building, using, and learning about databases.",
  },
  {
    id: 24,
    follow: "follow",
    hide: "hide",
    tag: "#frontend",
    number: "10,560",
    content: "If you're already a front-end developer, well, pretend you're also wearing a pirate hat.- Ethan Marcotte",
  },
  {
    id: 25,
    follow: "follow",
    hide: "hide",
    tag: "#api",
    number: "12,508",
    content: "Application Programming Interface",
  },
  {
    id: 26,
    follow: "follow",
    hide: "hide",
    tag: "#html",
    number: "22,031",
    content: "Hypertext Markup Language — the standard markup language for documents designed to be displayed in a",
  },
  {
    id: 26,
    follow: "follow",
    hide: "hide",
    tag: "#security",
    number: "15,194",
    content: "Hopefully",
  },
  {
    id: 25,
    follow: "follow",
    hide: "hide",
    tag: "#go",
    number: "14,748",
    content: "A statically typed, compiled programming language designed at Google",
  },
  {
    id: 26,
    follow: "follow",
    hide: "hide",
    tag: "#php",
    number: "15,708",
    content: "Home for all the PHP-related posts on Dev.to!",
  },
  {
    id: 27,
    follow: "follow",
    hide: "hide",
    tag: "#github",
    number: "17,741",
    content: "Where the world builds software",
  },
  {
    id: 28,
    follow: "follow",
    hide: "hide",
    tag: "#cloud",
    number: "14,069",
    content: "There is no cloud, only other peoples computers.",
  },
  {
    id: 29,
    follow: "follow",
    hide: "hide",
    tag: "#development",
    number: "10,522",
    content: "",
  },
  {
    id: 30,
    follow: "follow",
    hide: "hide",
    tag: "#android",
    number: "27,499",
    content: "Brought to you by the good folks at Google...",
  },
  {
    id: 31,
    follow: "follow",
    hide: "hide",
    tag: "#angular",
    number: "14,579",
    content: "One of the world's most popular frontend JavaScript frameworks.",
  },
  {
    id: 32,
    follow: "follow",
    hide: "hide",
    tag: "#coding",
    number: "8,691",
    content: "while (!(succeed = try()))",
  },
  {
    id: 33,
    follow: "follow",
    hide: "hide",
    tag: "#nextjs",
    number: "12,288",
    content: "Next.js gives you hybrid static and server rendering, TypeScript support, smart bundling, route pre-fetching, and more.",
  },
  {
    id: 34,
    follow: "follow",
    hide: "hide",
    tag: "#docker",
    number: "13,794",
    content: "Stories about Docker as a technology (containers, CLI, Engine) or company (Docker Hub, Docker Swarm).",
  },
  {
    id: 35,
    follow: "follow",
    hide: "hide",
    tag: "#softwaredevelopment",
    number: "8,807",
    content: "",
  },
  {
    id: 36,
    follow: "follow",
    hide: "hide",
    tag: "#codenewbie",
    number: "24,010",
    content: "The most supportive community of programmers and people learning to code.",
  },
  {
    id: 37,
    follow: "follow",
    hide: "hide",
    tag: "#coding",
    number: "8,691",
    content: "while (!(succeed = try()))",
  },
  {
    id: 38,
    follow: "follow",
    hide: "hide",
    tag: "#mobile",
    number: "14,599",
    content: "iOS, Android, and any other types of mobile development... all are welcome!",
  },
  {
    id: 39,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },
  {
    id: 40,
    follow: "follow",
    hide: "hide",
    tag: "#kubernets",
    number: "12,730",
    content: "An open-source container orchestration system for automating software deployment, scaling, and management.",
  },
  {
    id: 41,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },
  {
    id: 42,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },

  {
    id: 43,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },
  {
    id: 44,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },

  {
    id: 45,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },

  {
    id: 46,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },

  {
    id: 47,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },

  {
    id: 48,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },

  {
    id: 49,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },
  {
    id: 50,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },
  {
    id: 51,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },
  {
    id: 52,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },
  {
    id: 53,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },
  {
    id: 54,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },
  {
    id: 55,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },
  {
    id: 56,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },
  {
    id: 57,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },

  {
    id: 58,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },
  {
    id: 59,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },
  {
    id: 60,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },
  {
    id: 61,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },
  {
    id: 62,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },
  {
    id: 63,
    follow: "follow",
    hide: "hide",
    tag: "#laravel",
    number: "9,727",
    content: "A PHP web application framework with expressive, elegant syntax.",
  },


]